[package]
name = "canwu-technology"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Technology simulation domain extension for Canwu"

[dependencies]
canwu-api.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
